#!/usr/bin/env python3
# coding: utf-8
"""
RADIO UNDERGROUND v2 - tools/anchorview.py
See every HAND-AUTHORED anchor drawn on the backdrop, labelled with the exact
numbers to edit. Then edit them in assets/anchors/<ID>.data.js and re-run.

    py tools\\anchorview.py STORE-BACK-A          # state A
    py tools\\anchorview.py STORE-BACK-A B        # state B (fx that only exist in B)
    py tools\\anchorview.py STORE-INT-A

    -> tools/review/<ID>.anchors.png

WHAT YOU MAY EDIT BY HAND (canon -- the tools never touch these):
    spawns    [x,y]            the player's feet
    exits     rect [x,y,w,h]   + to, spawn, and optional face ('up'/'down'/...)
    hotspots  rect [x,y,w,h]   + face, op
    fx        at [x,y]         *** the CENTRE of the effect, not its corner ***
    npcSlots  [x,y]            an NPC's feet

WHAT YOU MUST NEVER HAND-EDIT (generated by mask2json.py):
    mask   walkBehind   grid

FOOT BOX: the engine's Mask.canStand tests a 12px-wide, 4px-deep patch --
px-6..px+5 and py-4..py-1. So a spawn needs clear floor 6px either side and
4px above its feet, and the outer 6px of any doorway are unusable. This tool
checks with the same rule the engine uses, so its verdicts are the real ones.
"""
import sys, os, re

try:
    from PIL import Image, ImageDraw
except ModuleNotFoundError:
    sys.exit("Missing pillow:  py -m pip install pillow")

GREEN=(80,255,120); YELL=(255,215,80); BLUE=(90,210,255); PINK=(255,120,200)
RED=(255,70,70); GREY=(150,150,150)

def load(ID):
    p=os.path.join('assets','anchors',f'{ID}.data.js')
    if not os.path.isfile(p): sys.exit(f'no anchors file: {p}')
    return open(p,encoding='utf-8').read().replace('\r','')

def decode_mask(src):
    m=re.search(r"mask:'([^']*)'",src)
    if not m: return None
    g=int(re.search(r'grid:(\d+)',src).group(1))
    cells=[]
    for run in m.group(1).split(','):
        n,v=run.split(':'); cells+= [int(v)]*int(n)
    return cells,g,768//g,432//g

def make_stand(mask):
    if not mask: return lambda x,y: True
    cells,g,cw,ch=mask
    def at(x,y):
        cx,cy=int(x)//g,int(y)//g
        return 0<=cx<cw and 0<=cy<ch and cells[cy*cw+cx]>0
    # the engine's foot box, verbatim from src/core/mask.js
    return lambda px,py: (at(px-6,py-1) and at(px+5,py-1)
                          and at(px-6,py-4) and at(px+5,py-4))

def block(src,name):
    i=src.find(name+':{')
    if i<0: return {}
    seg=src[i+len(name)+2:]
    seg=seg[:seg.index('}')]
    return {m[0]:(int(m[1]),int(m[2])) for m in re.findall(r'(\w+):\[(\d+),(\d+)\]',seg)}

def main():
    if len(sys.argv)<2: sys.exit('usage: py tools\\anchorview.py <ROOM-ID> [STATE]')
    ID=sys.argv[1]; state=(sys.argv[2] if len(sys.argv)>2 else 'A').upper()
    src=load(ID)

    # the backdrop shown is the STATE's backdrop; the mask is the state's too
    st=re.search(r"states:\{([^}]*)\}",src)
    bd=ID
    if st:
        mm=re.search(state+r":'([\w-]+)'",st.group(1))
        if mm: bd=mm.group(1)
    bp=os.path.join('assets','backdrops','normalized',f'{bd}.png')
    if not os.path.isfile(bp): sys.exit(f'no backdrop: {bp}')

    msrc=src
    if bd!=ID and os.path.isfile(os.path.join('assets','anchors',f'{bd}.data.js')):
        cand=load(bd)
        if "mask:'" in cand: msrc=cand
    stand=make_stand(decode_mask(msrc))

    im=Image.open(bp).convert('RGB').resize((1536,864),Image.NEAREST)
    d=ImageDraw.Draw(im)
    problems=[]

    def rect(r,col,label,ok=True):
        x,y,w,h=r
        d.rectangle([x*2,y*2,(x+w)*2,(y+h)*2],outline=(col if ok else RED),width=3)
        d.text((x*2+3,y*2-12),label,fill=(col if ok else RED))
    def dot(p,col,label,ok=True):
        x,y=p
        c=col if ok else RED
        d.ellipse([x*2-7,y*2-7,x*2+7,y*2+7],outline=c,width=3)
        d.line([x*2-11,y*2,x*2+11,y*2],fill=c); d.line([x*2,y*2-11,x*2,y*2+11],fill=c)
        d.text((x*2+12,y*2-6),label,fill=c)

    print(f'== {ID} (state {state}, backdrop {bd}) ==\n')

    for name,p in block(src,'spawns').items():
        okp=stand(*p)
        dot(p,BLUE,f'spawn:{name} {p}',okp)
        print(f'  spawn {name:12} {str(p):12} {"ok" if okp else "** SOLID - player spawns stuck **"}')
        if not okp: problems.append(f'spawn {name}')

    for rect_s,to,rest in re.findall(r"rect:\[([\d,]+)\],to:'([\w-]+)'([^}]*)",src):
        r=[int(v) for v in rect_s.split(',')]
        face=re.search(r"face:'(\w+)'",rest)
        pts=[(x,y) for x in range(r[0],r[0]+r[2],2) for y in range(r[1],r[1]+r[3],2)]
        pct=100*sum(stand(*q) for q in pts)/len(pts)
        okp=pct>=80
        lbl=f'EXIT->{to}' + (f' (face {face.group(1)})' if face else '')
        rect(r,GREEN,lbl,okp)
        print(f'  exit  {str(r):20} -> {to:14} {pct:5.0f}% standable '
              f'{"" if okp else "** unreachable **"}')
        if not okp: problems.append(f'exit -> {to}')

    for hid,rect_s,face in re.findall(r"\{id:'(\w+)',\s*rect:\[([\d,]+)\],\s*face:'(\w+)'",src):
        r=[int(v) for v in rect_s.split(',')]
        rect(r,YELL,f'{hid} ^{face}')
        print(f'  hot   {hid:12} {str(r):20} face={face}')

    for kind,at_s,fstate in re.findall(r"\{kind:'(\w+)',at:\[(\d+,\d+)\],state:'(\w+)'",src):
        if fstate!='AB' and state not in fstate:
            continue
        p=tuple(int(v) for v in at_s.split(','))
        dot(p,GREY,f'fx:{kind} {p} (centre)')
        # draw the true footprint of each effect so mis-aim is obvious
        box={'onAir':(52,24),'tubeGlow':(84,60),'deskLamp':(52,46)}.get(kind)
        if box:
            w,h=box
            d.rectangle([(p[0]-w//2)*2,(p[1]-h//2)*2,(p[0]+w//2)*2,(p[1]+h//2)*2],
                        outline=GREY,width=2)
        print(f'  fx    {kind:12} at {str(p):12} state={fstate}  (at = CENTRE)')

    for name,p in block(src,'npcSlots').items():
        dot(p,PINK,name)
        print(f'  npc   {name:12} {str(p):12} {"floor" if stand(*p) else "on furniture"}')

    os.makedirs(os.path.join('tools','review'),exist_ok=True)
    out=os.path.join('tools','review',f'{ID}.anchors.png' if state=='A'
                     else f'{ID}-{state}.anchors.png')
    im.save(out)
    print(f'\nwrote {out}')
    if problems:
        print('\n** FIX THESE in assets/anchors/%s.data.js: %s' % (ID, ', '.join(problems)))
        sys.exit(1)
    print('all anchors land on legal ground.')

if __name__=='__main__':
    main()
