#!/usr/bin/env python3
# coding: utf-8
"""
RADIO UNDERGROUND v2 - tools/build_songs.py
Scans assets/songs/*.song.js and rewires index.html + tools/harness.js so
every converted song is loaded. Run it after mid2song.py. Idempotent.

WHY THIS EXISTS
  SONG_LIST.md has 87 cues. Hand-adding 87 <script> tags in two files, in
  the right order, is exactly the kind of one-off work this project doesn't
  do. Author in a real tool, convert, then let a tool wire it up.

HOW A SONG REPLACES A BUILD-004 TRACK
  src/core/songs.js declares the seven original tracks as SONGS.main,
  SONGS.store, SONGS.copycat, SONGS.battle, SONGS.muzak, SONGS.boss,
  SONGS.victory. Every .song.js runs AFTER songs.js and does S[id]=...
  So a song whose id matches a legacy name simply OVERWRITES it:

      py tools\\mid2song.py store_morning.mid store     -> replaces SONGS.store
      py tools\\mid2song.py my_tune.mid       main      -> replaces SONGS.main

  Nothing in main.js changes; Music.play('store') just plays your track.
  The legacy oscillator code stays where it is, unused. That is the
  intended path for retiring every note the crew ever wrote.

  Use a NEW id instead when the cue is new (e.g. main_leitmotif), and call
  it explicitly from main.js.

USAGE
    py tools\\build_songs.py            # rewire, report
    py tools\\build_songs.py --check    # report only; exit 1 if out of date
"""
import sys, os, re, glob

INDEX   = 'index.html'
HARNESS = os.path.join('tools', 'harness.js')
SONGDIR = os.path.join('assets', 'songs')

BEG = '<!-- SONGS:BEGIN (generated by tools/build_songs.py) -->'
END = '<!-- SONGS:END -->'
HBEG = '/* SONGS:BEGIN (generated by tools/build_songs.py) */'
HEND = '/* SONGS:END */'

LEGACY = {'main', 'store', 'copycat', 'battle', 'muzak', 'boss', 'victory'}

def song_ids():
    out = []
    for p in sorted(glob.glob(os.path.join(SONGDIR, '*.song.js'))):
        src = open(p, encoding='utf-8').read()
        m = re.search(r'S\[\s*"([^"]+)"\s*\]', src) or re.search(r"S\[\s*'([^']+)'\s*\]", src)
        sid = m.group(1) if m else os.path.basename(p)[:-len('.song.js')]
        out.append((sid, p.replace('\\', '/')))
    return out

def block_html(songs):
    lines = [BEG]
    for sid, path in songs:
        tag = '   <!-- REPLACES the Build-004 track -->' if sid in LEGACY else ''
        lines.append(f'<script src="{path}"></script>{tag}')
    lines.append(END)
    return '\n'.join(lines)

def block_js(songs):
    lines = [HBEG]
    for _, path in songs:
        lines.append(f"  '{path}',")
    lines.append('  ' + HEND)
    return '\n'.join(lines)

def splice(text, beg, end, block, anchor_after):
    """Replace an existing marked block, or create one after `anchor_after`."""
    if beg in text and end in text:
        return re.sub(re.escape(beg) + r'.*?' + re.escape(end), block, text, flags=re.S), True
    if anchor_after not in text:
        sys.exit(f"ERROR: could not find anchor {anchor_after!r}")
    return text.replace(anchor_after, anchor_after + '\n' + block, 1), False

def main():
    check = '--check' in sys.argv
    if not os.path.isdir(SONGDIR):
        sys.exit("ERROR: assets/songs not found. Run from the project root.")
    songs = song_ids()
    if not songs:
        sys.exit("no *.song.js found — run mid2song.py first")

    print(f"{len(songs)} song(s) in {SONGDIR}:")
    for sid, p in songs:
        note = '  <-- OVERRIDES the Build-004 track' if sid in LEGACY else ''
        print(f"   {sid:28} {p}{note}")
    still = sorted(LEGACY - {s for s, _ in songs})
    if still:
        print(f"\nstill on Build-004 oscillators: {', '.join(still)}")
        print("   (name a converted song with one of those ids to replace it)")

    ih = open(INDEX, encoding='utf-8').read()
    hh = open(HARNESS, encoding='utf-8').read()
    new_ih, had_i = splice(ih, BEG, END, block_html(songs),
                           '<script src="src/core/songs.js"></script>')
    new_hh, had_h = splice(hh, HBEG, HEND, block_js(songs),
                           "'src/core/clock.js','src/core/songs.js',")

    stale = (new_ih != ih) or (new_hh != hh)
    if check:
        print("\nOUT OF DATE — run without --check" if stale else "\nup to date")
        sys.exit(1 if stale else 0)

    if new_ih != ih:
        open(INDEX, 'w', encoding='utf-8').write(new_ih)
        print(f"\n{'updated' if had_i else 'created'} SONGS block in {INDEX}")
    if new_hh != hh:
        open(HARNESS, 'w', encoding='utf-8').write(new_hh)
        print(f"{'updated' if had_h else 'created'} SONGS block in {HARNESS}")
    if not stale:
        print("\nalready up to date")
    print("\nnow run: node tools\\harness.js")

if __name__ == '__main__':
    main()
