/* RADIO UNDERGROUND v2 — tools/harness.js
   Logic playthrough harness, Phase 1 suite. Runs the REAL scripts
   headless and asserts the acceptance mechanics:
     clock math, judgement windows, sequencer scheduling, mask RLE
     integrity, collision, walk-behind sort, camera clamp, exits,
     input consume, update-budget sanity.
   Exit code 0 = green. Usage: node tools/harness.js */
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const {makeEnv}=require('./softcanvas');
const ROOT=path.join(__dirname,'..');
const SCRIPTS=['src/core/font.js','src/core/font_ext.js','src/core/input.js','src/core/audio.js',
  'src/core/voices.js','src/core/clock.js','src/core/songs.js',
/* SONGS:BEGIN (generated by tools/build_songs.py) */
  'assets/songs/main_leitmotif.song.js',
  'assets/songs/the_journey_continues.song.js',
  /* SONGS:END */
  'src/core/loader.js',
  'src/core/camera.js','src/core/mask.js','src/core/stage.js',
  'src/game/sprites.js','assets/sprites/IZZY.sprite.js',
  'assets/sprites/NOAH.sprite.js','assets/sprites/SALTMAN.sprite.js',
  'assets/anchors/STORE-BACK-A.data.js',
  'assets/anchors/STORE-INT-A.data.js','assets/anchors/STORE-INT-B.data.js',
  'assets/anchors/STORE-BACK-B.data.js','src/main.js'];

let pass=0,fail=0;
function ok(cond,name){cond?pass++:fail++;
  console.log((cond?'  PASS ':'X FAIL '),name);}

async function main(){
  const env=makeEnv();const ctx=vm.createContext(env);
  const SoftImage=env.Image;
  env.Image=class extends SoftImage{set src(p){super.src=path.join(ROOT,p);}};
  for(const s of SCRIPTS)
    vm.runInContext(fs.readFileSync(path.join(ROOT,s),'utf8'),ctx,{filename:s});
  const R=(js)=>vm.runInContext(js,ctx);
  await new Promise(r=>setImmediate(r));env.step(16.7);env.step(16.7);

  console.log('== LOADER ==');
  ok(R('Loader.ready')===true,'ready gate fires');
  ok(R('Loader.failed.length')===0,'no failed images');
  ok(R('Loader.img("STORE-BACK-A").width')===768,'BACK-A is 768 wide');

  console.log('== SONGBOOK IMPORT ==');
  ok(typeof R('SONGS["the_journey_continues"]')==='object','imported .song.js registered');
  ok(R('SONGS["the_journey_continues"].bpm')===140,'imported bpm 140');
  ok(R('SONGS["the_journey_continues"].imported')===1,'flagged imported (routes to session players)');
  ok(R('SONGS["the_journey_continues"].parts.every(p=>typeof p.voice==="string")'),
     'every imported part names a voice');
  ok(R('SONGS["the_journey_continues"].drLoop')===R('SONGS["the_journey_continues"].len'),
     'drums absolute across song (drLoop===len)');
  ok(R('SONGS.main.parts.every(p=>typeof p.w==="string"&&p.voice===undefined)'),
     'Build 004 tracks untouched (still w:, no voice)');
  ok(typeof R('vVoice')==='function'&&typeof R('vDrumX')==='function','session players present');

  console.log('== BOOT -> INTRO -> ROAM ==');
  env.tap('z');env.step(16.7);
  ok(R('Game.mode')==='intro','Z leaves title for the opening crawl');
  ok(R('Music.name')==='','tuning still ebbing: the song has not burst in yet');
  // the song bursts in at F_CRAWL_IN (frame 72), not on the keypress
  for(let i=0;i<80;i++)env.step(16.7);
  ok(R('Music.name')==='the_journey_continues','opening theme playing (imported)');
  ok(R('Clock.running&&Clock.bpm===140'),'clock running at imported bpm 140');
  for(let i=0;i<8;i++)env.step(16.7);
  ok(R('Music.ptr')>0,'imported song schedules events on the clock');
  ok(R('CRAWL.length')>30&&R('CRAWL.join(" ").indexOf("HANDSHAKE")')>=0,
     'long canon crawl installed (Scene 1)');
  ok(R('CRAWL.join("|").indexOf("OR SO THEY THOUGHT")')<0,
     'the two closing lines are centre cards, not part of the scroll');
  ok(R('F_SCENE_2')>R('F_TUNE_BACK')&&R('F_TUNE_BACK')>R('F_SONG_FADE'),
     'staging order: song fades -> tuning returns -> Scene 2');
  env.tap('z');env.step(16.7);
  ok(R('Game.mode')==='roam','Z leaves the crawl for the store');
  ok(R('Stage.roomId')==='STORE-INT-A','opens in STORE-INT-A (Scene 2)');
  ok(R('Music.name')==='main_leitmotif','leitmotif playing (producer MIDI)');
  ok(R('Clock.running&&Clock.bpm===186'),'clock running at leitmotif bpm 186');
  ok(R('SONGS.main_leitmotif.imported')===1,'leitmotif routes to session players');

  console.log('== SCENE 2 ROOM SKELETON (STORE-INT-A) ==');
  ok(typeof R('ROOMS["STORE-INT-A"]')==='object','STORE-INT-A registered');
  ok(typeof R('ROOMS["STORE-INT-A"].mask')==='string'&&R('ROOMS["STORE-INT-A"].mask.length')>100,
     'mask painted + converted (mask2json ran)');
  ok(R('ROOMS["STORE-INT-A"].walkBehind.length')>0,'walkBehind strips generated from occl paint');
  // anchors must agree with the paint: spawns stand on floor, exit is reachable.
  ok(R('(function(){const m=Mask.decode(ROOMS["STORE-INT-A"],"STORE-INT-A");'+
     'return Object.values(ROOMS["STORE-INT-A"].spawns).every(p=>Mask.canStand(m,p[0],p[1]))})()'),
     'every spawn stands on walkable floor');
  ok(R('(function(){const m=Mask.decode(ROOMS["STORE-INT-A"],"STORE-INT-A");'+
     'const e=ROOMS["STORE-INT-A"].exits[0].rect;let n=0;'+
     'for(let x=e[0];x<e[0]+e[2];x+=2)for(let y=e[1];y<e[1]+e[3];y+=2)if(Mask.canStand(m,x,y))n++;'+
     'return n>0})()'),
     'exit trigger sits on reachable floor');
  ok(R('ROOMS["STORE-INT-A"].exits[0].to')==='STORE-BACK-A','bead-curtain exit targets the back room');
  ok(R('ROOMS["STORE-INT-A"].hotspots.some(h=>h.id==="zamfir")'),'Zamfir gag has an anchor (protected)');
  ok(R('ROOMS["STORE-INT-A"].npcSlots.stylus!==undefined'),'Stylus has a slot on the SALE crate (protected)');
  ok(R('Object.keys(ROOMS["STORE-INT-A"].spawns).length')===3,'three spawns: default/fromBack/fromStreet');
  ok(R('ROOMS["STORE-INT-A"].hotspots.every(h=>h.rect[0]>=0&&h.rect[1]>=0&&h.rect[0]+h.rect[2]<=768&&h.rect[1]+h.rect[3]<=432)'),
     'every hotspot rect inside 768x432');

  // roam now opens in STORE-INT-A; the geometry suite below is authored
  // against STORE-BACK-A's paint, so step back into it deliberately.
  R('enterRoom("STORE-BACK-A","default")');env.step(16.7);
  ok(R('Stage.roomId')==='STORE-BACK-A','can walk back through the STAFF ONLY door');

  console.log('== CLOCK MATH == (the one non-negotiable)');
  // freeze a known time AND a known tempo. The judgement windows are absolute
  // ms, so these offsets only mean what we think they mean if a half-beat is
  // wider than WIN_GOOD. At 186bpm a half-beat is 161ms and a "200ms late"
  // press is really 123ms EARLY for the next beat -> GOOD. Pin bpm=96.
  R('Clock.t0=0');R('Clock.bpm=96');env._ac.currentTime=10*R('Clock.beatLen()'); // exactly beat 10
  ok(Math.abs(R('Clock.msOffBeat()'))<1e-6,'msOffBeat=0 exactly on the beat');
  env._ac.currentTime=10.5*R('Clock.beatLen()');
  const half=R('Clock.msOffBeat()');
  ok(Math.abs(half-R('Clock.beatLen()')*500)<1e-6,'half-beat = beatLen/2 ms');
  env._ac.currentTime=10*R('Clock.beatLen()')+0.065; // 65ms late
  ok(R('judgePress()')==='PERFECT','65ms -> PERFECT (win 70)');
  env._ac.currentTime=10*R('Clock.beatLen()')+0.100;
  ok(R('judgePress()')==='GOOD','100ms -> GOOD (win 125)');
  env._ac.currentTime=10*R('Clock.beatLen()')+0.200;
  ok(R('judgePress()')==='OFF','200ms -> OFF');
  ok(R('Clock.phase()')>=0&&R('Clock.phase()')<1,'phase in [0,1)');

  console.log('== SEQUENCER ==');
  const n0=R('Music.ptr');R('Music.tick()');env._ac.currentTime+=0.5;R('Music.tick()');
  ok(R('Music.ptr')>n0,'lookahead scheduler advances');
  ok(R('Music.evts.every((e,i,a)=>i===0||a[i-1].b<=e.b)'),'event list sorted');

  console.log('== MASK ==');
  ok(R('roomMask.cw===Math.ceil(768/roomMask.grid)&&'+
       'roomMask.ch===Math.ceil(432/roomMask.grid)'),
     'cell counts match room size / grid (grid='+R('roomMask.grid')+')');
  const total=R('roomMask.cells.length');
  ok(total===R('roomMask.cw*roomMask.ch'),'RLE decodes to full cell count');
  ok(R('Mask.at(roomMask,384,330)')===1,'spawn cell walkable');
  ok(R('Mask.at(roomMask,300,100)')===0,'shelf wall solid');
  const nBehind=R('(function(){let n=0;for(const v of roomMask.cells)'+
    'if(v===2)n++;return n})()');
  const bcell=nBehind?R('(function(){for(let i=0;i<roomMask.cells.length;i++)'+
    'if(roomMask.cells[i]===2)return {x:(i%roomMask.cw)*roomMask.grid+2,'+
    'y:((i/roomMask.cw)|0)*roomMask.grid+2}})()'):null;
  ok(nBehind===0||R(`Mask.at(roomMask,${bcell&&bcell.x},${bcell&&bcell.y})`)===2,
     nBehind?'painted corridor cell decodes as walk-behind (2)':
     'no blue authored — corridors optional, occluders carry occlusion');
  ok(nBehind===0?R('Mask.isBehind(roomMask,384,330)')===false:
     R(`Mask.isBehind(roomMask,${bcell&&bcell.x},${bcell&&bcell.y})`)===true,
     'isBehind agrees with the paint');

  console.log('== COLLISION ==');
  R('Player.px=384;Player.py=330');
  env.key('ArrowUp',true);
  for(let i=0;i<200;i++)env.step(16.7);
  env.key('ArrowUp',false);
  const py=R('Player.py');
  ok(R(`Mask.canStand(roomMask,384,${py})&&!Mask.canStand(roomMask,384,${py-2})`),
     'up-walk at x384 stops exactly at a painted boundary (py='+py+')');
  R('Player.px=516;Player.py=330');
  env.key('ArrowUp',true);
  for(let i=0;i<200;i++)env.step(16.7);
  env.key('ArrowUp',false);
  const py2=R('Player.py');
  ok(py2<300&&R(`Mask.canStand(roomMask,516,${py2})&&!Mask.canStand(roomMask,516,${py2-2})`),
     'up-walk at x516 crosses open floor, stops at a painted boundary (py='+py2+')');
  R('Player.px=560;Player.py=330');
  env.key('ArrowUp',true);
  for(let i=0;i<200;i++)env.step(16.7);
  env.key('ArrowUp',false);
  const py3=R('Player.py');
  ok(R(`Mask.canStand(roomMask,560,${py3})&&!Mask.canStand(roomMask,560,${py3-2})`),
     'up-walk at x560 stops at a painted boundary (py='+py3+')');
  R('Player.px=384;Player.py=330');
  env.key('ArrowLeft',true);
  for(let i=0;i<300;i++)env.step(16.7);
  env.key('ArrowLeft',false);
  const px=R('Player.px');
  ok(px>0&&R(`Mask.canStand(roomMask,${px},330)&&!Mask.canStand(roomMask,${px-2},330)`),
     'left-walk stops at a painted boundary, never escapes the room (px='+px+')');

  console.log('== 8-WAY MOVEMENT (diagonal-ready) ==');
  ok(R("dir8(0,1)==='down'&&dir8(0,-1)==='up'&&dir8(-1,0)==='left'&&dir8(1,0)==='right'"),
     'dir8 resolves the four cardinals');
  ok(R("dir8(-1,-1)==='upleft'&&dir8(1,-1)==='upright'&&dir8(-1,1)==='downleft'&&dir8(1,1)==='downright'"),
     'dir8 resolves the four diagonals');
  // diagonal speed is normalized: net displacement ~2px/frame, not 2*sqrt2
  const spot=R('(function(){const m=roomMask;for(let y=90;y<390;y+=4)for(let x=90;x<690;x+=4){'+
    'if(Mask.canStand(m,x,y)&&Mask.canStand(m,x+3,y-3))return[x,y];}return null;})()');
  ok(!!spot,'found open floor to measure a diagonal step');
  if(spot){
    R('Player.px='+spot[0]+';Player.py='+spot[1]+';Player.step=0');
    env.key('ArrowUp',true);env.key('ArrowRight',true);
    R('updatePlayer()');
    env.key('ArrowUp',false);env.key('ArrowRight',false);
    const net=R('Math.hypot(Player.px-'+spot[0]+',Player.py-'+spot[1]+')');
    ok(Math.abs(net-2)<0.05,'diagonal net speed ~2px/frame (got '+net.toFixed(3)+'), not '+(2*Math.SQRT2).toFixed(2));
    ok(R("Player.dir==='upright'"),'two-key input faces the diagonal (upright)');
  }
  // every built facing set exposes all 8 keys; a 4-row sheet aliases diagonals
  ok(R("['down','up','left','right','downleft','downright','upleft','upright']"+
       ".every(d=>Array.isArray(BOX[d])&&BOX[d].length>=3)"),
     'placeholder exposes all 8 facings');
  ok(R("BOX.downleft===BOX.left&&BOX.downright===BOX.right&&BOX.upleft===BOX.left&&BOX.upright===BOX.right"),
     '4-row diagonals alias to their cardinal (no missing facing)');
  ok(R("(function(){const s=PlayerSpr;return s&&['downleft','downright','upleft','upright']"+
       ".every(d=>Array.isArray(s[d])&&s[d].length>=3)})()"),
     "Mike's 4-row sheet also exposes aliased diagonals");

  console.log('== REAL 8-ROW SHEET (producer art through buildSheet) ==');
  // Izzy is a real producer-drawn 8-row sheet, sliced by the engine's own
  // buildSheet. She is NOT the player, so this exercises the real slice path
  // without disturbing the deterministic box the pixel tests rely on.
  ok(R("!!SPRITE_SHEETS['IZZY']&&SPRITE_SHEETS['IZZY'].rows===8"),
     'IZZY sheet registered as 8 rows');
  ok(R("(function(){const s=buildSheet('IZZY');return s&&['down','up','left','right',"+
       "'downleft','downright','upleft','upright'].every(d=>Array.isArray(s[d])&&s[d].length===3)})()"),
     'buildSheet slices IZZY into all 8 facings, 3 frames each');
  // a 4-row sheet ALIASES diagonals to a cardinal (same array ref); a real
  // 8-row sheet fills rows 4-7, so the references must differ. This is what
  // proves the producer's diagonal art actually made it into the sheet.
  ok(R("(function(){const s=buildSheet('IZZY');return s.downleft!==s.left&&s.downright!==s.right"+
       "&&s.upleft!==s.left&&s.upright!==s.right})()"),
     'IZZY diagonals are real rows, not cardinal aliases');
  // every sliced frame matches the sheet's registered native cell (32x48 at
  // scale 1, 64x96 at the 2x detail build) — buildSheet slices to meta.cell,
  // and stage.js downsamples that into the fixed on-screen box, so this stays
  // true across a resolution bump without pinning a literal here.
  ok(R("(function(){const c=SPRITE_SHEETS['IZZY'].cell,s=buildSheet('IZZY');"+
       "return s.down[0].width===c[0]&&s.down[0].height===c[1]})()"),
     'sliced frames match the registered cell size');
  // NOAH and SALTMAN join the cast as real 8-row producer sheets (Phase 2,
  // pending visual approval). Same structural checks Izzy passed: registered as
  // 8 rows, sliced into all 8 facings x3 frames, diagonals distinct from their
  // cardinals (proves the diagonal art landed, not aliased).
  for(const ID of ['NOAH','SALTMAN']){
    ok(R(`!!SPRITE_SHEETS['${ID}']&&SPRITE_SHEETS['${ID}'].rows===8`),
       ID+' sheet registered as 8 rows');
    ok(R(`(function(){const s=buildSheet('${ID}');return s&&['down','up','left','right',`+
         `'downleft','downright','upleft','upright'].every(d=>Array.isArray(s[d])&&s[d].length===3)})()`),
       'buildSheet slices '+ID+' into all 8 facings, 3 frames each');
    ok(R(`(function(){const s=buildSheet('${ID}');return s.downleft!==s.left&&s.downright!==s.right`+
         `&&s.upleft!==s.left&&s.upright!==s.right})()`),
       ID+' diagonals are real rows, not cardinal aliases');
  }

  console.log('== WALK-BEHIND SORT ==');
  const spots=behindSpots(R);
  ok(spots.length>=1,'reachable floor behind occluders: '+
     spots.map(s=>s.note).join(',')||'none');
  const s0=spots[0]||{x:300,y:210};
  // strip joins y-sort at horizon: above -> occluded, below -> in front
  R(`Player.px=${s0.x};Player.py=${s0.y}`); // behind the first occluder
  env.step(16.7);
  const ok1=R('(function(){const bx0=Player.px-16,bx1=Player.px+16;'+
    'return Stage.room.walkBehind.filter(w=>w.x<bx1&&w.x+w.w>bx0'+
    '&&w.y<Player.py&&w.y+w.h>Player.py-48)'+
    '.every(w=>w.horizon>Player.py)})()');
  ok(ok1,'corridor sprite sorts BEFORE every strip overlapping it');
  R('Player.py=300');
  const order2=R('(function(){const o=[{y:Player.py,s:1},'+
    '{y:Stage.room.walkBehind[0].horizon}];o.sort((a,b)=>a.y-b.y);'+
    'return o.findIndex(x=>x.s)})()');
  ok(order2===1,'floor sprite sorts AFTER the shelf strip (in front)');
  // pixel-truth: corridor player must be hidden by the re-blitted shelf
  R(`Player.px=${s0.x};Player.py=${s0.y};Camera.snap()`);env.step(16.7);
  const bx0=Math.max(s0.x-16,s0.sx),bx1=Math.min(s0.x+16,s0.sx+s0.sw),
        byT=Math.max(s0.y-44,s0.sy);
  ok(!scanBox(env,[201,168,63],bx0-R('Camera.ix()'),byT-R('Camera.iy()'),
     bx1-bx0,s0.y-byT),
     'pixel scan: body re-blitted behind '+s0.note);
  R('Player.px=384;Player.py=330;Camera.snap()');env.step(16.7);
  ok(scanFor(env,[201,168,63]),'pixel scan: box-sprite visible on open floor');

  console.log('== CAMERA CLAMP ==');
  R('Player.px=20;Player.py=220;Camera.snap()');
  ok(R('Camera.ix()')===0,'clamps at x=0 (left edge)');
  ok(R('Camera.iy()')===Math.max(0,Math.min(162,220-16-135)),
     'y follows unclamped mid-range (=69)');
  R('Player.px=20;Player.py=206;Camera.snap()');
  ok(R('Camera.iy()')===206-16-135,'y tracks toward top, >=0 held');
  R('Player.px=750;Player.py=425;Camera.snap()');
  ok(R('Camera.ix()')===768-480&&R('Camera.iy()')===432-270,
     'clamps at 288,162 (bottom-right)');

  console.log('== INPUT CONSUME ==');
  env.key('z',true); // held
  env.step(16.7);env.step(16.7);
  ok(R('Keys.hit.A')===undefined||R('Keys.hit.A')===false,
     'held Z fires hit once, cleared by frame end (no re-fire)');
  env.key('z',false);

  console.log('== EXIT RUNNER (rooms actually connect) ==');
  R('enterRoom("STORE-BACK-A","default");Game.flags._exitArmed=true;toasts.length=0');
  R('Player.px=130;Player.py=122;Player.dir="up"'); // BACK-A: STAFF ONLY doorway
  env.step(16.7);
  ok(R('Stage.roomId')==='STORE-INT-A','back-room door lands in the store');
  ok(R('Mask.canStand(roomMask,Player.px,Player.py)'),'arrives standing on floor (fromBack)');
  R('Player.dir="up"');                             // face the door we arrived through
  for(let i=0;i<6;i++)env.step(16.7);               // spawn sits IN the store doorway
  ok(R('Stage.roomId')==='STORE-INT-A','no ping-pong: exits disarmed until you step clear');
  R('Player.px=200;Player.py=140');env.step(16.7);  // step clear -> re-arm
  R('Player.px=124;Player.py=56;Player.dir="up"');env.step(16.7);   // STAFF ONLY door
  ok(R('Stage.roomId')==='STORE-BACK-A','STAFF ONLY door leads back');
  // facing guard: standing in the door walking sideways must NOT leave
  R('enterRoom("STORE-INT-A","default");Game.flags._exitArmed=true');
  R('Player.px=124;Player.py=56;Player.dir="right"');env.step(16.7);
  ok(R('Stage.roomId')==='STORE-INT-A','walking past the door sideways does not exit');
  R('enterRoom("STORE-BACK-A","default");Game.flags._exitArmed=true');env.step(16.7);
  ok(R('Mask.canStand(roomMask,Player.px,Player.py)'),'arrives standing on floor (fromStore)');

  // A door you cannot stand in is not a door. This is generic: it walks every
  // room's exits, so a misplaced rect can never ship again. (STORE-BACK-A's
  // was at the bottom of the room by the GOOD MUSIC sign: 30% walkable.)
  ok(R('(function(){for(var id in ROOMS){var rm=ROOMS[id];'+
     'if(!rm.exits||!rm.mask)continue;var m=Mask.decode(rm,id);'+
     'for(var i=0;i<rm.exits.length;i++){var e=rm.exits[i].rect,n=0,t=0;'+
     'for(var x=e[0];x<e[0]+e[2];x+=2)for(var y=e[1];y<e[1]+e[3];y+=2){t++;'+
     'if(Mask.canStand(m,x,y))n++;}'+
     'if(n/t<0.8)return false;}}return true})()'),
     'every exit rect in every room is >=80% walkable floor');
  ok(R('(function(){for(var id in ROOMS){var rm=ROOMS[id];'+
     'if(!rm.exits)continue;'+
     'for(var i=0;i<rm.exits.length;i++){var e=rm.exits[i];'+
     'if(!ROOMS[e.to])return false;'+
     'if(!ROOMS[e.to].spawns||!ROOMS[e.to].spawns[e.spawn])return false;}}'+
     'return true})()'),
     'every exit names a room that exists, with the spawn it asks for');

  console.log('== PER-STATE FLOORS ==');
  ok(R('typeof Stage.dataFor')==='function','stage resolves room data per state');
  ok(R('ROOMS["STORE-INT-B"]&&typeof ROOMS["STORE-INT-B"].mask==="string"'),
     'STORE-INT-B carries its own painted mask');
  ok(R('(function(){enterRoom("STORE-INT-A","default");var a=Stage.dataFor();'+
       'Stage.state="B";var b=Stage.dataFor();Stage.state="A";'+
       'return a===ROOMS["STORE-INT-A"]&&b===ROOMS["STORE-INT-B"]})()'),
     'state B resolves to the STORE-INT-B floor, not A\'s');
  ok(R('(function(){enterRoom("STORE-INT-A","default","B");'+
       'var g=roomMask&&roomMask.grid===4;enterRoom("STORE-INT-A","default");return g})()'),
     'entering state B decodes B\'s mask');

  console.log('== FONT ==');
  ok(R('FONT[">"]!==undefined')&&R('FONT["<"]!==undefined'),
     'arrow glyphs exist (no more "EXIT -?")');

  // back to BACK-A, armed, for the occluder geometry suite below
  R('enterRoom("STORE-BACK-A","default");Game.flags._exitArmed=true');env.step(16.7);

  console.log('== GENERATED OCCLUDERS (occl.png pipeline) ==');
  ok(R('Stage.room.walkBehind.length')>=12,'strips generated from occl paint');
  ok(R('Stage.room.walkBehind.every(w=>w.note&&w.note.indexOf("occl-")===0)'),
     'all strips carry generated notes');
  // prove body-hidden behind every sampled blob; head-visible where it can poke
  let proven=0,headOK=0,headTried=0;
  for(const s of spots.slice(0,4)){
    R(`Player.px=${s.x};Player.py=${s.y};Camera.snap()`);env.step(16.7);
    const x0=Math.max(s.x-16,s.sx),x1=Math.min(s.x+16,s.sx+s.sw),
          yT=Math.max(s.y-44,s.sy);
    if(!scanBox(env,[201,168,63],x0-R('Camera.ix()'),yT-R('Camera.iy()'),
       x1-x0,s.y-yT))proven++;
    if(s.y-48<s.sy-4){headTried++;
      if(scanBox(env,[201,168,63],s.x-16-R('Camera.ix()'),
         (s.y-48)-R('Camera.iy()'),32,(s.sy-4)-(s.y-48)))headOK++;}
  }
  ok(proven===Math.min(spots.length,4),
     'body re-blitted behind every sampled occluder ('+proven+'/'+
     Math.min(spots.length,4)+')');
  ok(headTried===0||headOK>0,
     'head visible above an occluder top ('+headOK+'/'+headTried+' where possible)');
  // in FRONT: just below the first blob's horizon, sprite must survive
  const frontS=spots.find(s=>R(`Mask.canStand(roomMask,${s.x},${s.hz+8})`));
  if(frontS){R(`Player.px=${frontS.x};Player.py=${frontS.hz+8};Camera.snap()`);env.step(16.7);}
  ok(!frontS||scanFor(env,[201,168,63]),
     frontS?('in front of '+frontS.note+' (below horizon): sprite not eaten'):
     'no floor below any horizon — in-front case vacuous');

  console.log('== CONTACT SHADOW vs OCCLUDERS ==');
  // The shadow is drawn inside the sprite's y-sort entry, immediately before
  // the sprite image, so a strip re-blitted after it must erase BOTH. Proven
  // in pixels: render the frame, then re-render with no sprites at the same
  // camera, and diff the band at the player's feet.
  {
    const feetDiff=(px,py)=>R('(function(){'+
      'Player.px='+px+';Player.py='+py+';Player.dir="down";Player.anim=0;'+
      'Camera.follow(Player);Camera.snap();'+
      'Stage.draw(cx,[{px:Player.px,py:Player.py,img:BOX[Player.dir][Player.anim]}],{t:0});'+
      'var a=cx.getImageData(0,0,VIEW_W,VIEW_H).data;'+
      'Stage.draw(cx,[],{t:0});'+
      'var b=cx.getImageData(0,0,VIEW_W,VIEW_H).data;'+
      'var cy=Camera.iy(),cx0=Camera.ix();'+
      'var sy=Math.floor(Player.py-cy),sx=Math.floor(Player.px-cx0),n=0;'+
      'for(var y=sy-3;y<=sy+2;y++)for(var x=sx-14;x<=sx+14;x++){'+
      ' if(x<0||y<0||x>=VIEW_W||y>=VIEW_H)continue;'+
      ' var i=(y*VIEW_W+x)*4;'+
      ' if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>10)n++;}'+
      'return n;})()');
    R('enterRoom("STORE-INT-A","default");BOX=BOX||buildPlaceholder()');
    const H=88;                       // counter blob: strips y44..88, horizon 88
    const behind=feetDiff(250,H-16);  // player behind the counter
    const front =feetDiff(250,H+16);  // player in front of it
    ok(behind===0,'shadow is erased with the body when behind an occluder ('+behind+' px)');
    ok(front>0,'shadow draws normally in front of an occluder ('+front+' px)');
    R('enterRoom("STORE-BACK-A","default");Game.flags._exitArmed=true');env.step(16.7);
  }

  console.log('== UPDATE BUDGET ==');
  const t0=Date.now();
  for(let i=0;i<300;i++)env.step(16.7);
  const ms=(Date.now()-t0)/300;
  console.log('   softcanvas frame avg '+ms.toFixed(2)+'ms (browser is far faster)');
  ok(ms<50,'headless frame under 50ms sanity bound');

  console.log('\n'+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
}
function behindSpots(R){
  // one standable point per occluder blob (py < horizon), derived from
  // the GENERATED strips + the painted mask — never hardcoded geometry
  return R('(function(){const out=[],seen={};'+
    'for(const w of Stage.room.walkBehind){'+
      'if(seen[w.note])continue;'+
      'for(let y=w.y+6;y<Math.min(w.y+w.h,w.horizon-2)&&!seen[w.note];y+=4)'+
        'for(let x=w.x+12;x<=w.x+w.w-12;x+=4)'+
          'if(Mask.canStand(roomMask,x,y)){seen[w.note]=1;'+
            'out.push({note:w.note,x:x,y:y,sx:w.x,sw:w.w,sy:w.y,hz:w.horizon});break;}'+
    '}return out})()');
}
function scanBox(env,rgb,x,y,w,h){
  const px=env.screen._px,W=env.screen.width;
  for(let yy=Math.max(0,y);yy<Math.min(env.screen.height,y+h);yy++)
    for(let xx=Math.max(0,x);xx<Math.min(W,x+w);xx++){
      const i=(yy*W+xx)*4;
      if(Math.abs(px[i]-rgb[0])<7&&Math.abs(px[i+1]-rgb[1])<7&&
         Math.abs(px[i+2]-rgb[2])<7)return true;
    }
  return false;
}
function scanFor(env,rgb){ // tolerance covers the grading tint pass
  const px=env.screen._px;
  for(let i=0;i<px.length;i+=4)
    if(Math.abs(px[i]-rgb[0])<7&&Math.abs(px[i+1]-rgb[1])<7&&
       Math.abs(px[i+2]-rgb[2])<7)return true;
  return false;
}
main().catch(e=>{console.error(e);process.exit(1);});
